### ISSUE TITLE
TDI should not intercept link click when clicked with ctrl key

### ISSUE THREAD

**Issue by msevcenko** [twinstone/tdi#10]
When link is clicked with a ctrl key pressed, the user indicates that he wants to open the result into a new window. I think that TDI should in this case just ignore the TDI condition and progress with the default behavior, which is sending normal request and opening the result to a new window.

Maybe this behavior may be preventable (indicated by class, or data attribute), if the author of the link knows that opening to a new window has no sense and TDI in the current window should take place anyway.

Such as like this:

```javascript
function _onBeforeLinkClick( evt ) {
 			if (evt.ctrlKey) {
 				// do not intercept ctrl+key
 				return;
 			}
			evt.preventDefault();
			...
}
```

**Comment by centi** [comment]
Check for other means for opening in new tab (like middleclick) as well.

**Comment by msevcenko** [comment]
Middleclick worked even without this fix, it is probably different event so IMO it was never intercepted by TDI (at least on windows).
