### ISSUE TITLE
Allow custom attributes for default update/insert instructions

### ISSUE THREAD

**Issue by mishal** [twinstone/tdi#12]
Our use case:

    <update target="#target" custom-attribute="value" />

Js hook:

    $(document).on('tdi:ajax:beforeUpdate', function (e, eventData) {
      var $target = eventData.target;
      // there no access to the original tag attributes
    });

As per [docs](https://docs.twinstone.org/doc/tdi/1.7/classes/TDI.Ajax.Response.html#event_tdi:ajax:beforeUpdate) there are several properties of the event playload available, but there is no access to the original tag attributes (like in [_onBeforeUnknown](https://github.com/twinstone/tdi/blob/master/src/js/tdi-ajax.js#L1269)).

I patched the TDI function which triggers the event and includes the additional tag attributes. I can now access the tag attribute:

    $(document).on('tdi:ajax:beforeUpdate', function (e, eventData) {
      var $target = eventData.target;
      var $tag = eventData.tag;
      var customAttribute = eventData.attributes['custom-attribute'];
      // do something cool :-)
    });

We use the attribute to decide if the UI should highlight another element. We used script instructions before, but it was problematic.

Could TDI include the additional/original tag attributes for update and insert instructions?

**Comment by centi** [comment]
Maybe I could pass the whole XML tag structure. You could extract the attributes from it yourself but also have the possibility to do something more with the tag.

**Comment by mishal** [comment]
yes, that would be more flexible.

**Comment by mishal** [comment]
what name will be the best? (I can prepare the PR). simple `tag: $tag` would work for me.

**Comment by centi** [comment]
Yes, "tag" is OK.

**Comment by mishal** [comment]
PR #23
