### ISSUE TITLE
Treat update/insert target attribute as ID

### ISSUE THREAD

**Issue by centi** [twinstone/tdi#14]
Sometimes, the ID attribute (used as target) contains characters which have special meaning in CSS selectors (dot, colon). Using $(id) method causes troubles in these cases.

As the target attribute must contain only ID anyway, TDI should use something like this to find the target element: $(document.getElementById(target))

**Comment by mishal** [comment]
We never use anything special in the target attribute, just simple id.

**Comment by centi** [comment]
ID attribute can contain also a dot `.` and a colon `:` (see. https://www.w3.org/TR/html401/types.html#type-name).

So there is a chance, that a valid ID attribute will not work with TDI and the `$(id)` call. This is the reason for this issue.
