### ISSUE TITLE
Script instructions do not work sequentially

### ISSUE THREAD

**Issue by centi** [twinstone/tdi#15]
When a TDI response carries two script instructions, one with src and the other one inlined, the first one is not completely loaded before the second one starts. If the second instruction depends on definitions made by the first one, it may fail unexpectedly.

Example:

```xml
<status>OK</status>
<script id="demo-hiding-support" src="some-file.js"></script>
<script>
    someFunctionX();
</script>
```

If the someFunctionX is defined in the some-file.js, the very first call fails saying it is not defined yet. Repeated invocation do work.

**Comment by strakz1** [comment]
Already fixed?

**Comment by centi** [comment]
No, this is not fixed yet.

**Comment by centi** [comment]
I'm afraid there is no cross-domain way to implement this (synchronously download and execute scripts).

We could add a new `returns` (or `provides`) attribute to the `script` instruction. It would specify, what the loaded script provides ($ object for loaded jQuery, CKEDITOR object for wysiwyg, etc). TDI then could use this information to postpone loading the next script (external or inline) to the moment, when the return value is available = previous script is loaded and executed.

This would of course expect the external scripts to be written a specific way.
