### ISSUE TITLE
TypeError: $(…).unload is not a function (JQuery 3.0)

### ISSUE THREAD

**Issue by mishal** [twinstone/tdi#17]
The function `$(window).unload` has been removed in JQuery 3, see:  http://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed

Fix: `$(window).on('unload', func)`

**Comment by sachinms15** [comment]
After referencing below 2 jquery url
https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js
https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js

I am getting below error message
Uncaught TypeError: $(...).unload is not a function
What is the fix?
