### ISSUE TITLE
Selector attribute is not documented

### ISSUE THREAD

**Issue by mishal** [twinstone/tdi#22]
The `selector` attribute for update/insert instruction is not documented:

https://wiki.twinstone.org/display/TDI/update

The target attribute is documented as **required** but the implementation allows selector attribute to be present and it takes precedence before the target. (see: https://github.com/twinstone/tdi/blob/master/src/js/tdi-ajax.js#L961)

**Comment by centi** [comment]
Thanks for pointing out. I updated the documentation, see:

* https://wiki.twinstone.org/display/TDI/update
* https://wiki.twinstone.org/display/TDI/insert
