### ISSUE TITLE
Coding style spec

### ISSUE THREAD

**Issue by mishal** [twinstone/tdi#24]
What coding style does TDI use? 

Could it be reformatted using any well known one so eslint or another tool can be used to check the source?

**Comment by centi** [comment]
Hi. There is no particular coding style used. Which one do you suggest?

**Comment by mishal** [comment]
Google style: https://google.github.io/styleguide/jsguide.html ?

There is a nice preset for Eslint: http://eslint.org/docs/user-guide/migrating-from-jscs#converting-presets which makes the linting easy.

We use additional rules for:

 * http://eslint.org/docs/rules/prefer-spread (disable)
 * http://eslint.org/docs/rules/no-var  (disable)
 * http://eslint.org/docs/rules/prefer-rest-params  (disable)
 * http://eslint.org/docs/rules/max-len (255 chars)

**Comment by centi** [comment]
Space indentation is a no-go for me. I will check other guides.

**Comment by mishal** [comment]
You can simply extend the existing styles and customize it to fit your preferences: use tab instead space.

**Comment by centi** [comment]
I know. There is a new branch called "style-guide", where I added some jshint and jscs rules (based on Airbnb style guide) and reformatted the code accordingly.

**Comment by centi** [comment]
Do you have a windows machine available? I added a pre-commit git hook, which runs the tests and linting, but I have only a Mac with me. I would like to know, if the hook runs ok on Windows (after checking out the branch, you need to run npm install again).

**Comment by mishal** [comment]
Hi in 2017! :)

The hook works ok on my win machine. (Win 7 Pro)!

I propose to run the linting tests also on Travis.
