### ISSUE TITLE
Builds on Travis are failing

### ISSUE THREAD

**Issue by mishal** [twinstone/tdi#41]
Builds on Travis are failing since  v1.9.2

**Comment by centi** [comment]
Could you please elaborate? What does it fail on? Can you attach a log?

**Comment by centi** [comment]
Ok, sorry. I forgot that there is a button in the readme :)

**Comment by centi** [comment]
I had to update the travis config to enforce a newer version of Node.

**Comment by mishal** [comment]
Thanks!
